/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ups.ejercicio_03_05.View;

import java.awt.Color;

/**
 *
 * @author Diego
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuEmpresa = new javax.swing.JMenu();
        jMenuItemEmpresa = new javax.swing.JMenuItem();
        jMenuDepartamento = new javax.swing.JMenu();
        jMenuItemDep = new javax.swing.JMenuItem();
        jMenuEmpleado = new javax.swing.JMenu();
        jMenuItemEmpleado = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenimiento Empresa - Departamento - Empleado");

        jDesktopPane1.setBackground(new java.awt.Color(60, 7, 135));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );

        jMenuEmpresa.setText("Empresa");

        jMenuItemEmpresa.setText("Agregar/Editar");
        jMenuEmpresa.add(jMenuItemEmpresa);

        jMenuBar1.add(jMenuEmpresa);

        jMenuDepartamento.setText("Departamento");

        jMenuItemDep.setText("Agregar/Editar");
        jMenuDepartamento.add(jMenuItemDep);

        jMenuBar1.add(jMenuDepartamento);

        jMenuEmpleado.setText("Empleado");

        jMenuItemEmpleado.setText("Agregar/Editar");
        jMenuEmpleado.add(jMenuItemEmpleado);

        jMenuBar1.add(jMenuEmpleado);

        jMenuExit.setText("Salir");
        jMenuExit.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuExitMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuExitMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuExitMenuSelected
        this.dispose();
    }//GEN-LAST:event_jMenuExitMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDepartamento;
    private javax.swing.JMenu jMenuEmpleado;
    private javax.swing.JMenu jMenuEmpresa;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenuItem jMenuItemDep;
    private javax.swing.JMenuItem jMenuItemEmpleado;
    private javax.swing.JMenuItem jMenuItemEmpresa;
    // End of variables declaration//GEN-END:variables
}
